### ISSUE TITLE
Viewer zoom in on swipe in landscape mode

### ISSUE THREAD

**Issue by raymondkarstensen** [NationalLibraryOfNorway/ngx-mime#110]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Viewer should only swipe

#### What is the current behavior?
Viewer zoom in after swipe

#### What are the steps to reproduce?
1. Load viewer in portrait view
2. Go to Dashboard mode
3. Turn mobile to landscape view
4. Swipe in any direction

#### Which versions of Angular, OS, TypeScript, browsers are affected?
Just tested in chrome on android

#### Is there anything else we should know?

**Comment by ooystein** [comment]
I'll have a try at this one!

**Comment by ooystein** [comment]
Ok. have it solved. Will try to make a test for it also before I create a PR.
