### ISSUE TITLE
Viewer shows header and footer in page mode after error

### ISSUE THREAD

**Issue by raymondkarstensen** [NationalLibraryOfNorway/ngx-mime#111]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behavior?
Viewer should hide header & footer when in page mode

#### What is the current behavior?
Viewer does not hide header or footer 

#### What are the steps to reproduce?
1. Open demo app
2. Type random text in manifest input box
3. After error is displayed, click on link to any manifest in sidenav

#### Which versions of Angular, OS, TypeScript, browsers are affected?
All

#### Is there anything else we should know?

**Comment by stianmorsund** [comment]
Fixed by #109

**Comment by ronnymikalsen** [comment]
Fixed #114

**Comment by ronnymikalsen** [comment]
Fixed #114
