### ISSUE TITLE
AccessKeys

### ISSUE THREAD

**Issue by ronnymikalsen** [NationalLibraryOfNorway/ngx-mime#122]
#### Bug, feature request, or proposal:
Feature

#### What is the expected behavior?
Page down, right arrow, n -> Next page
Page up, left arrow, p -> Previous page
Home -> Go to first page
End -> Go to last page

plus -> zoom in
minus -> zoom out
0 -> zoom out to home

ALT + SHIFT + f - open search
ALT + SHIFT + c - open contents

Fullscreeen?

#### What is the use-case or motivation for changing an existing behavior?
Better user experience

**Comment by trondmyk** [comment]
Need a hotkey to clear search.  - suggestion SHIFT+S
