### ISSUE TITLE
Not able to close attribution dialog in fullscreen mode

### ISSUE THREAD

**Issue by raymondkarstensen** [NationalLibraryOfNorway/ngx-mime#222]
**Describe the bug**
When in fullscreen mode I'm not able to close the attribution dialog. It will only toggle between page mode and dashboard mode

**To Reproduce**

1.  Go to https://www.nb.no/search?mediatype=b%C3%B8ker
2.  Open any book
3.  Toggle fullsceen mode
4.  Try to close attribution dialog

**Expected behavior**
Attribution dialog should close the same way it does in page or dashboard mode

**Desktop (please complete the following information):**

* OS: Linux
* Browser Chrome
* Version 67.0.3396.62

**Smartphone (please complete the following information):**

* Device: Pixel & Galaxy S6
* OS: Android 8 & 7
* Browser Chrome
* Version 66.0.3359.158

**Comment by ronnymikalsen** [comment]
I think this bug is fixed by https://github.com/NationalLibraryOfNorway/ngx-mime/pull/273

**Comment by ronnymikalsen** [comment]
Fixed by https://github.com/NationalLibraryOfNorway/ngx-mime/pull/273
