### ISSUE TITLE
Dialogs not visible in fullscreen mode

### ISSUE THREAD

**Issue by jimarthurnilsen** [NationalLibraryOfNorway/ngx-mime#269]
**Describe the bug**
Overlay containers are not visible when viewer is in fullscreen mode.
- Attribution container
- Contents container
- Go to page container
- Search container

**To Reproduce**

1.  Start demo app in project
2.  Open up attribution manifest
3.  Set fullscreen mode
4.  Attribution dialog dissapears and you can't open other dialogs

**Expected behavior**
When in fullscreen mode you should be able to see all dialogs

**Desktop (please complete the following information):**

- OS: All
- Browser All
- Version All

**Smartphone (please complete the following information):**
Not tested on smartphone

**Which versions of NGX-Mime, Angular, Material, OS, TypeScript, browsers are affected?**
Only tested latest version

**Comment by raymondkarstensen** [comment]
Fixed https://github.com/NationalLibraryOfNorway/ngx-mime/pull/273
