### ISSUE TITLE
Recognized text content view hides image when using hotkey

### ISSUE THREAD

**Issue by ronnymikalsen** [NationalLibraryOfNorway/ngx-mime#359]
**Describe the bug**
Recognized text content view hides image when using hotkey.

**To Reproduce**

1.  Open demoapp
2.  Open "Recognized text"
3.  Use hotkey 't'
4.  See error

**Expected behavior**
Recognized text content should not block image

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Which versions of NGX-Mime, Angular, Material, OS, TypeScript, browsers are affected?**
Ngx-mime v12.2.8

**Additional context**

**Comment by jimarthurnilsen** [comment]
fixed by https://github.com/NationalLibraryOfNorway/ngx-mime/pull/361
