### ISSUE TITLE
Can't navigate between search hits if multiple hits on a single page using hits navigator in footer

### ISSUE THREAD

**Issue by jimarthurnilsen** [NationalLibraryOfNorway/ngx-mime#395]
**Describe the bug**
If you search for something that gives multiple hits on a page you can't navigate between each hit using the hit navigator in the footer.
If there are multiple search hits on current page and on other pages the next button is enabled and will jump directly to next page with hits. If there are only hits on a single page both prev/next button are disabled. 

**To Reproduce**

1.  Open demo app
2.  Open Recognized text manifest
3.  Search for "this" for multiple pages example and "by" for the singlepage example
4.  Try navigating between search hits in footer

**Expected behavior**
When I search for "this" in the recognized text manifest I expect to be able to use the hit navigator in the footer to navigate between multiple hits on the same page

**Screenshots**
![image](https://user-images.githubusercontent.com/12290169/153183630-95a97a32-635a-4a72-a245-cb894015efc3.png)
![image](https://user-images.githubusercontent.com/12290169/153183678-88bd4d74-5abe-43ee-adcc-ddce5e460831.png)

**Which versions of NGX-Mime, Angular, Material, OS, TypeScript, browsers are affected?**
All

**Additional context**
If you first search for "this" and then swap query to "by" then the navigation button is enabled but doesn't work. Same goes the other way. If you first search for "by" and then swap query to "this" the buttons are disabled and you can't navigate.

**Comment by ronnymikalsen** [comment]
Fixed by #409
